shell = "zsh"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-replace-multiple-dots]
github = "momo-lab/zsh-replace-multiple-dots"

[plugins.z]
github = "rupa/z"
